package structure.impl.qeas;

public enum QEAType {
	QVAR01_FVAR_DET_QEA,
	QVAR01_FVAR_NONDET_QEA,
	QVAR01_NOFVAR_DET_QEA,
	QVAR01_NOFVAR_NONDET_QEA,
	QVAR1_FVAR_DET_FIXEDQVAR_QEA,
	QVAR1_FVAR_NONDET_FIXEDQVAR_QEA
}
